data_dir:
figure_dir:
db_file: sdc.db
target_file: map.csv
command_logfile: commands.log

notify_slack: true
plot_slack: true
test: false

solutions:
    0: {'A': 1.0}

syringe_diamater: 29.5

frame_orientation: '-y'
pump_array_port: 'COM12'
camera_index: 2

default_experiment: [{"op": "lsv", "initial_potential": -1.1, "final_potential": 0.2, "scan_rate": 0.01, "current_range": "20MA"}]
default_flowrate: {"op": "set_flow", "pH": 7, "flow_rate": 1.25, "relative_rates": {"A": 1.0}, "purge_time": 90}

# expect the human to start the experiment with the cell
initial_combi_position:
  x: 0.0
  y: 0.0

# motion controller speed in m/s
speed: 1e-3

# use INTERNAL/EXTERNAL cell
cell: EXTERNAL

# add a delay before running each experiment...
initial_delay: 0

confirm: False
confirm_experiment: False

# ease off vertically before moving the cell laterally
# step height in meters
step_height: 0.002

cleanup_pause: 30
fill_rate: 1
fill_counter_ratio: 0.5
fill_time: 4
shrink_counter_ratio: 1.
shrink_time: 1
